server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: profile_service
          uri: http://localhost:8080
          predicates:
          - Path=${app.api-prefix}/profile/**
          filters:
          - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: partner-session
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/partnersession/**
          filters:
            - StripPrefix=2
